name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: 16.x

    # Instalar as dependências do yarn
    - name: Install dependencies
      run: yarn 

    # Executar a build
    - name: Run build
      run: yarn build

    - name: Debug Secrets
      run: |
        echo "${{ secrets.SSH_HOST }}"
        echo "${{ secrets.SSH_USER }}"
        echo "Port: ${{ secrets.SSH_PORT }}"
        echo "Key (first 10 chars): ${SSH_KEY:0:10}"


    - name: Test SSH connection
      run: ssh -i <(echo "${{ secrets.SSH_KEY }}" | tr -d '\r') -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo 'SSH connection successful'"  

    # Copiar a pasta dist para dentro da Digital Ocean
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist"
        target: "test"
        args: "-vvv"
