name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: 16.x

    # Instalar as dependências do yarn
    - name: Install dependencies
      run: yarn 

    # Executar a build
    - name: Run build
      run: yarn build

    # Copiar código para dentro da Digital Ocean
    - name: Copy dist to Digital Ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        timeout: 120s
        source: ".,!node_modules"
        target: "~/app/backend-money-checking"
        
    # Executar yarn, migrations e reiniciar o servidor na Digital Ocean
    - name: Run production scripts
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/app/backend-money-checking
          yarn
          ./node_modules/.bin/typeorm migration:run
          pm2 restart moneychecking-api
